### ISSUE TITLE
Is this library suitable for WPF applications?

### ISSUE THREAD

**Issue by JawadJaber** [awaescher/FluentTransitions#2]
I really liked the potential and the easiness of using animations this library provides, however, I see the sample app is made with WinForms. Therefore, I wonder if it supports WPF as well?

**Comment by awaescher** [comment]
I did not try it yet, but I see no problem. These transitions are basically just helper classes setting properties in a times way, with intelligent value interpolation.

As I'm writing I think that there could be a thing that could go bad with WPF: the handling of the SynchronzationContext. So I'd encourage you to just try it. Please let me know what you found.

**Comment by awaescher** [comment]
I just checked: There is a dependency to `System.Windows.Forms` (`net48` or `netcoreapp3.1`, depending on your runtime). But it is just to check if an object is disposed yet (`System.Windows.Forms.Control` has two properties for this: `Disposing` and `IsDisposed`). This check will just do nothing for other object types or other platforms like WPF.

If you don't mind this reference, yes - it is suitable for WPF.
